/**
 * Submit all sitemap URLs to IndexNow (Bing, Seznam, Naver, Yandex…).
 * Run after each deploy that adds/changes pages: node scripts/indexnow.mjs
 * The key file /<key>.txt is generated by build-seo.mjs.
 */
const SITE = 'https://cv.zalize.com'
const KEY = '88d13cb021bb7d759cc09d7b95af03fc'

// cache-bust so we read the freshly deployed sitemap, not the CDN cache
const res = await fetch(`${SITE}/sitemap.xml?v=${Date.now()}`)
if (!res.ok) throw new Error(`sitemap fetch failed: ${res.status}`)
const xml = await res.text()
const urls = [...xml.matchAll(/<loc>([^<]+)<\/loc>/g)].map((m) => m[1])
if (urls.length === 0) throw new Error('no URLs found in sitemap')

const submit = await fetch('https://api.indexnow.org/indexnow', {
  method: 'POST',
  headers: { 'content-type': 'application/json; charset=utf-8' },
  body: JSON.stringify({
    host: 'cv.zalize.com',
    key: KEY,
    keyLocation: `${SITE}/${KEY}.txt`,
    urlList: urls,
  }),
})
console.log(`submitted ${urls.length} URLs → HTTP ${submit.status}`)
if (!submit.ok) console.error(await submit.text())
